version: '3.9'

volumes:
  db_data:

services:
  db:
    image: postgres:15.1-alpine
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  web:
    build:
      context: ./inviting_app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: >
      sh -c "
        python3 manage.py makemigrations && 
        python3 manage.py migrate &&
        gunicorn inviting_app.wsgi:application --bind 0:8000
      "
